name: Publish overlay electron app

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

  publish:
    needs: ["lint"]
    strategy:
      matrix:
        os:
          - version: ubuntu-latest
            cmd: linux
          - version: windows-latest
            cmd: windows
          - version: macos-latest
            cmd: macos
    runs-on: ${{ matrix.os.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('overlay/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: cd overlay && yarn install

      - name: Build, Make and Publish to GitHub
        run: cd overlay && yarn publish:${{ matrix.os.cmd }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
